/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { NeosantaraError } from "./neosantaraerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export const Code = {
  MissingApiKey: "missing_api_key",
  InvalidApiKey: "invalid_api_key",
  ExpiredApiKey: "expired_api_key",
} as const;
export type Code = ClosedEnum<typeof Code>;

export type AuthErrorError = {
  message: string;
  type: string;
  code: Code;
};

/**
 * Error jika API key salah/kurang.
 */
export type AuthErrorData = {
  error?: AuthErrorError | undefined;
  /**
   * Metadata response dari NusantaraAI.
   */
  metadata?: components.Metadata | undefined;
};

/**
 * Error jika API key salah/kurang.
 */
export class AuthError extends NeosantaraError {
  error?: AuthErrorError | undefined;
  /**
   * Metadata response dari NusantaraAI.
   */
  metadata?: components.Metadata | undefined;

  /** The original data that was passed to this error instance. */
  data$: AuthErrorData;

  constructor(
    err: AuthErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.metadata != null) this.metadata = err.metadata;

    this.name = "AuthError";
  }
}

/** @internal */
export const Code$inboundSchema: z.ZodNativeEnum<typeof Code> = z.nativeEnum(
  Code,
);

/** @internal */
export const Code$outboundSchema: z.ZodNativeEnum<typeof Code> =
  Code$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Code$ {
  /** @deprecated use `Code$inboundSchema` instead. */
  export const inboundSchema = Code$inboundSchema;
  /** @deprecated use `Code$outboundSchema` instead. */
  export const outboundSchema = Code$outboundSchema;
}

/** @internal */
export const AuthErrorError$inboundSchema: z.ZodType<
  AuthErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  type: z.string(),
  code: Code$inboundSchema,
});

/** @internal */
export type AuthErrorError$Outbound = {
  message: string;
  type: string;
  code: string;
};

/** @internal */
export const AuthErrorError$outboundSchema: z.ZodType<
  AuthErrorError$Outbound,
  z.ZodTypeDef,
  AuthErrorError
> = z.object({
  message: z.string(),
  type: z.string(),
  code: Code$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthErrorError$ {
  /** @deprecated use `AuthErrorError$inboundSchema` instead. */
  export const inboundSchema = AuthErrorError$inboundSchema;
  /** @deprecated use `AuthErrorError$outboundSchema` instead. */
  export const outboundSchema = AuthErrorError$outboundSchema;
  /** @deprecated use `AuthErrorError$Outbound` instead. */
  export type Outbound = AuthErrorError$Outbound;
}

export function authErrorErrorToJSON(authErrorError: AuthErrorError): string {
  return JSON.stringify(AuthErrorError$outboundSchema.parse(authErrorError));
}

export function authErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<AuthErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthErrorError' from JSON`,
  );
}

/** @internal */
export const AuthError$inboundSchema: z.ZodType<
  AuthError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => AuthErrorError$inboundSchema).optional(),
  _metadata: components.Metadata$inboundSchema.optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_metadata": "metadata",
    });

    return new AuthError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type AuthError$Outbound = {
  error?: AuthErrorError$Outbound | undefined;
  _metadata?: components.Metadata$Outbound | undefined;
};

/** @internal */
export const AuthError$outboundSchema: z.ZodType<
  AuthError$Outbound,
  z.ZodTypeDef,
  AuthError
> = z.instanceof(AuthError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      error: z.lazy(() => AuthErrorError$outboundSchema).optional(),
      metadata: components.Metadata$outboundSchema.optional(),
    }).transform((v) => {
      return remap$(v, {
        metadata: "_metadata",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthError$ {
  /** @deprecated use `AuthError$inboundSchema` instead. */
  export const inboundSchema = AuthError$inboundSchema;
  /** @deprecated use `AuthError$outboundSchema` instead. */
  export const outboundSchema = AuthError$outboundSchema;
  /** @deprecated use `AuthError$Outbound` instead. */
  export type Outbound = AuthError$Outbound;
}
