/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";
import { SDKError } from "./sdkerror.js";

/**
 * Error untuk request yang tidak valid.
 */
export type BadRequestErrorData = {
  error?: models.BadRequestErrorError | undefined;
  /**
   * Metadata response dari NusantaraAI.
   */
  metadata?: models.Metadata | undefined;
};

/**
 * Error untuk request yang tidak valid.
 */
export class BadRequestError extends SDKError {
  error?: models.BadRequestErrorError | undefined;
  /**
   * Metadata response dari NusantaraAI.
   */
  metadata?: models.Metadata | undefined;

  /** The original data that was passed to this error instance. */
  data$: BadRequestErrorData;

  constructor(
    err: BadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.metadata != null) this.metadata = err.metadata;

    this.name = "BadRequestError";
  }
}

/** @internal */
export const BadRequestError$inboundSchema: z.ZodType<
  BadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.BadRequestErrorError$inboundSchema).optional(),
  _metadata: models.Metadata$inboundSchema.optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_metadata": "metadata",
    });

    return new BadRequestError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type BadRequestError$Outbound = {
  error?: models.BadRequestErrorError$Outbound | undefined;
  _metadata?: models.Metadata$Outbound | undefined;
};

/** @internal */
export const BadRequestError$outboundSchema: z.ZodType<
  BadRequestError$Outbound,
  z.ZodTypeDef,
  BadRequestError
> = z.instanceof(BadRequestError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      error: z.lazy(() => models.BadRequestErrorError$outboundSchema)
        .optional(),
      metadata: models.Metadata$outboundSchema.optional(),
    }).transform((v) => {
      return remap$(v, {
        metadata: "_metadata",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BadRequestError$ {
  /** @deprecated use `BadRequestError$inboundSchema` instead. */
  export const inboundSchema = BadRequestError$inboundSchema;
  /** @deprecated use `BadRequestError$outboundSchema` instead. */
  export const outboundSchema = BadRequestError$outboundSchema;
  /** @deprecated use `BadRequestError$Outbound` instead. */
  export type Outbound = BadRequestError$Outbound;
}
