/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";
import { SDKError } from "./sdkerror.js";

/**
 * Error server internal.
 */
export type ServerErrorData = {
  error?: models.ServerErrorError | undefined;
  /**
   * Metadata response dari NusantaraAI.
   */
  metadata?: models.Metadata | undefined;
};

/**
 * Error server internal.
 */
export class ServerError extends SDKError {
  error?: models.ServerErrorError | undefined;
  /**
   * Metadata response dari NusantaraAI.
   */
  metadata?: models.Metadata | undefined;

  /** The original data that was passed to this error instance. */
  data$: ServerErrorData;

  constructor(
    err: ServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.metadata != null) this.metadata = err.metadata;

    this.name = "ServerError";
  }
}

/** @internal */
export const ServerError$inboundSchema: z.ZodType<
  ServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.ServerErrorError$inboundSchema).optional(),
  _metadata: models.Metadata$inboundSchema.optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_metadata": "metadata",
    });

    return new ServerError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ServerError$Outbound = {
  error?: models.ServerErrorError$Outbound | undefined;
  _metadata?: models.Metadata$Outbound | undefined;
};

/** @internal */
export const ServerError$outboundSchema: z.ZodType<
  ServerError$Outbound,
  z.ZodTypeDef,
  ServerError
> = z.instanceof(ServerError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      error: z.lazy(() => models.ServerErrorError$outboundSchema).optional(),
      metadata: models.Metadata$outboundSchema.optional(),
    }).transform((v) => {
      return remap$(v, {
        metadata: "_metadata",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ServerError$ {
  /** @deprecated use `ServerError$inboundSchema` instead. */
  export const inboundSchema = ServerError$inboundSchema;
  /** @deprecated use `ServerError$outboundSchema` instead. */
  export const outboundSchema = ServerError$outboundSchema;
  /** @deprecated use `ServerError$Outbound` instead. */
  export type Outbound = ServerError$Outbound;
}
