/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chatChatCompletions } from "../../funcs/chatChatCompletions.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.ChatCompletionsRequest$inboundSchema,
};

export const tool$chatChatCompletions: ToolDefinition<typeof args> = {
  name: "chat-chat-completions",
  description: `Create chat completion (OpenAI-Compatible)

Membuat completion chat seperti OpenAI API. Kirim array messages (role: user/assistant, content: string).`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await chatChatCompletions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
