/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { completionsTextCompletions } from "../../funcs/completionsTextCompletions.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.TextCompletionsRequest$inboundSchema,
};

export const tool$completionsTextCompletions: ToolDefinition<typeof args> = {
  name: "completions-text-completions",
  description: `OpenAI compatible completions (text only)

Membuat text completion menggunakan prompt string.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await completionsTextCompletions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
