/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { embeddingsEmbeddings } from "../../funcs/embeddingsEmbeddings.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.EmbeddingsRequest$inboundSchema,
};

export const tool$embeddingsEmbeddings: ToolDefinition<typeof args> = {
  name: "embeddings-embeddings",
  description: `Create embeddings (OpenAI-Compatible)

Membuat embedding dari input text.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await embeddingsEmbeddings(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
