/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { moderationsModerations } from "../../funcs/moderationsModerations.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.ModerationsRequest$inboundSchema,
};

export const tool$moderationsModerations: ToolDefinition<typeof args> = {
  name: "moderations-moderations",
  description: `Content moderation check

Melakukan pengecekan moderasi konten.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await moderationsModerations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
