/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsListModels } from "../../funcs/modelsListModels.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$modelsListModels: ToolDefinition = {
  name: "models-list-models",
  description: `List available models

Mendapatkan daftar model yang tersedia.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await modelsListModels(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
