/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reasoningReasoning } from "../../funcs/reasoningReasoning.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.ReasoningRequest$inboundSchema,
};

export const tool$reasoningReasoning: ToolDefinition<typeof args> = {
  name: "reasoning-reasoning",
  description: `Enhanced reasoning completion

Completion dengan enhanced reasoning capabilities.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await reasoningReasoning(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
