/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { systemSystemStatus } from "../../funcs/systemSystemStatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$systemSystemStatus: ToolDefinition = {
  name: "system-system-status",
  description: `System status and info

Mendapatkan status sistem dan informasi akun.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await systemSystemStatus(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
