/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usageUsage } from "../../funcs/usageUsage.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UsageRequest$inboundSchema.optional(),
};

export const tool$usageUsage: ToolDefinition<typeof args> = {
  name: "usage-usage",
  description: `Get usage statistics

Mendapatkan statistik penggunaan API.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usageUsage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
