/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { SDKCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$chatChatCompletions } from "./tools/chatChatCompletions.js";
import { tool$completionsTextCompletions } from "./tools/completionsTextCompletions.js";
import { tool$embeddingsEmbeddings } from "./tools/embeddingsEmbeddings.js";
import { tool$modelsListModels } from "./tools/modelsListModels.js";
import { tool$moderationsModerations } from "./tools/moderationsModerations.js";
import { tool$reasoningReasoning } from "./tools/reasoningReasoning.js";
import { tool$systemSystemStatus } from "./tools/systemSystemStatus.js";
import { tool$usageUsage } from "./tools/usageUsage.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  apiKeyAuth?: SDKOptions["apiKeyAuth"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "SDK",
    version: "0.0.1",
  });

  const client = new SDKCore({
    apiKeyAuth: deps.apiKeyAuth,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$chatChatCompletions);
  tool(tool$completionsTextCompletions);
  tool(tool$modelsListModels);
  tool(tool$embeddingsEmbeddings);
  tool(tool$moderationsModerations);
  tool(tool$usageUsage);
  tool(tool$reasoningReasoning);
  tool(tool$systemSystemStatus);

  return server;
}
