/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationCheckApiKeyStatus } from "../funcs/authenticationCheckApiKeyStatus.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Authentication extends ClientSDK {
  /**
   * Check API Key status
   *
   * @remarks
   * Check status and remaining usage of API Key.
   */
  async checkApiKeyStatus(
    options?: RequestOptions,
  ): Promise<operations.CheckApiKeyStatusResponseBody> {
    return unwrapAsync(authenticationCheckApiKeyStatus(
      this,
      options,
    ));
  }
}
