/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chatChatCompletions } from "../funcs/chatChatCompletions.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Chat extends ClientSDK {
  /**
   * Create chat completion
   *
   * @remarks
   * Generate chat responses from a list of messages.
   */
  async chatCompletions(
    request: components.ChatCompletionsRequest,
    options?: RequestOptions,
  ): Promise<components.ChatCompletionsResponse> {
    return unwrapAsync(chatChatCompletions(
      this,
      request,
      options,
    ));
  }
}
