/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chatChatCompletions } from "../funcs/chatChatCompletions.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Chat extends ClientSDK {
  /**
   * Create chat completion (OpenAI-Compatible)
   *
   * @remarks
   * Membuat completion chat seperti OpenAI API. Kirim array messages (role: user/assistant, content: string).
   */
  async chatCompletions(
    request: models.ChatCompletionsRequest,
    options?: RequestOptions,
  ): Promise<models.ChatCompletionsResponse> {
    return unwrapAsync(chatChatCompletions(
      this,
      request,
      options,
    ));
  }
}
