/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { completionsTextCompletions } from "../funcs/completionsTextCompletions.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Completions extends ClientSDK {
  /**
   * OpenAI compatible completions (text only)
   *
   * @remarks
   * Membuat text completion menggunakan prompt string.
   */
  async textCompletions(
    request: models.TextCompletionsRequest,
    options?: RequestOptions,
  ): Promise<models.TextCompletionResponse> {
    return unwrapAsync(completionsTextCompletions(
      this,
      request,
      options,
    ));
  }
}
