/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { embeddingsEmbeddings } from "../funcs/embeddingsEmbeddings.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Embeddings extends ClientSDK {
  /**
   * Create embeddings (OpenAI-Compatible)
   *
   * @remarks
   * Membuat embedding dari input text.
   */
  async embeddings(
    request: components.EmbeddingsRequest,
    options?: RequestOptions,
  ): Promise<components.EmbeddingsResponse> {
    return unwrapAsync(embeddingsEmbeddings(
      this,
      request,
      options,
    ));
  }
}
