/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { moderationsModerations } from "../funcs/moderationsModerations.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Moderations extends ClientSDK {
  /**
   * Content moderation check
   *
   * @remarks
   * Melakukan pengecekan moderasi konten.
   */
  async moderations(
    request: models.ModerationsRequest,
    options?: RequestOptions,
  ): Promise<models.ModerationsResponse> {
    return unwrapAsync(moderationsModerations(
      this,
      request,
      options,
    ));
  }
}
