/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsListModels } from "../funcs/modelsListModels.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Models extends ClientSDK {
  /**
   * List available models
   *
   * @remarks
   * Retrieve a list of all available models and their capabilities.
   */
  async listModels(
    options?: RequestOptions,
  ): Promise<components.ModelsListResponse> {
    return unwrapAsync(modelsListModels(
      this,
      options,
    ));
  }
}
