/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reasoningReasoning } from "../funcs/reasoningReasoning.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Reasoning extends ClientSDK {
  /**
   * Reasoning completion
   *
   * @remarks
   * Generate reasoning for complex problems.
   */
  async reasoning(
    request: components.ReasoningRequest,
    options?: RequestOptions,
  ): Promise<components.ChatCompletionsResponse> {
    return unwrapAsync(reasoningReasoning(
      this,
      request,
      options,
    ));
  }
}
