/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reasoningReasoning } from "../funcs/reasoningReasoning.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Reasoning extends ClientSDK {
  /**
   * Enhanced reasoning completion
   *
   * @remarks
   * Completion dengan enhanced reasoning capabilities.
   */
  async reasoning(
    request: models.ReasoningRequest,
    options?: RequestOptions,
  ): Promise<models.ChatCompletionsResponse> {
    return unwrapAsync(reasoningReasoning(
      this,
      request,
      options,
    ));
  }
}
