/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Chat } from "./chat.js";
import { Completions } from "./completions.js";
import { Embeddings } from "./embeddings.js";
import { Models } from "./models.js";
import { Moderations } from "./moderations.js";
import { Reasoning } from "./reasoning.js";
import { System } from "./system.js";
import { Usage } from "./usage.js";

export class Neosantara extends ClientSDK {
  private _chat?: Chat;
  get chat(): Chat {
    return (this._chat ??= new Chat(this._options));
  }

  private _completions?: Completions;
  get completions(): Completions {
    return (this._completions ??= new Completions(this._options));
  }

  private _models?: Models;
  get models(): Models {
    return (this._models ??= new Models(this._options));
  }

  private _embeddings?: Embeddings;
  get embeddings(): Embeddings {
    return (this._embeddings ??= new Embeddings(this._options));
  }

  private _moderations?: Moderations;
  get moderations(): Moderations {
    return (this._moderations ??= new Moderations(this._options));
  }

  private _usage?: Usage;
  get usage(): Usage {
    return (this._usage ??= new Usage(this._options));
  }

  private _reasoning?: Reasoning;
  get reasoning(): Reasoning {
    return (this._reasoning ??= new Reasoning(this._options));
  }

  private _system?: System;
  get system(): System {
    return (this._system ??= new System(this._options));
  }
}
