/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Authentication } from "./authentication.js";
import { Chat } from "./chat.js";
import { Embeddings } from "./embeddings.js";
import { Models } from "./models.js";
import { Moderations } from "./moderations.js";
import { Reasoning } from "./reasoning.js";

export class Neosantara extends ClientSDK {
  private _chat?: Chat;
  get chat(): Chat {
    return (this._chat ??= new Chat(this._options));
  }

  private _models?: Models;
  get models(): Models {
    return (this._models ??= new Models(this._options));
  }

  private _embeddings?: Embeddings;
  get embeddings(): Embeddings {
    return (this._embeddings ??= new Embeddings(this._options));
  }

  private _moderations?: Moderations;
  get moderations(): Moderations {
    return (this._moderations ??= new Moderations(this._options));
  }

  private _reasoning?: Reasoning;
  get reasoning(): Reasoning {
    return (this._reasoning ??= new Reasoning(this._options));
  }

  private _authentication?: Authentication;
  get authentication(): Authentication {
    return (this._authentication ??= new Authentication(this._options));
  }
}
