/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { systemSystemStatus } from "../funcs/systemSystemStatus.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class System extends ClientSDK {
  /**
   * System status and info
   *
   * @remarks
   * Mendapatkan status sistem dan informasi akun.
   */
  async systemStatus(
    options?: RequestOptions,
  ): Promise<models.SystemStatusResponse> {
    return unwrapAsync(systemSystemStatus(
      this,
      options,
    ));
  }
}
