/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usageUsage } from "../funcs/usageUsage.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Usage extends ClientSDK {
  /**
   * Get usage statistics
   *
   * @remarks
   * Mendapatkan statistik penggunaan API.
   */
  async usage(
    request?: operations.UsageRequest | undefined,
    options?: RequestOptions,
  ): Promise<components.UsageResponse> {
    return unwrapAsync(usageUsage(
      this,
      request,
      options,
    ));
  }
}
