/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the neosantara-ai SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx chatChatCompletions.ts
 */

import { Neosantara } from "neosantara-ai";

const neosantara = new Neosantara({
  apiKey: process.env["NEOSANTARA_API_KEY"] ?? "",
});

async function main() {
  const result = await neosantara.chatCompletions({
    model: "nusantara-base",
    messages: [
      {
        role: "system",
        content: "<value>",
      },
    ],
  });

  console.log(result);
}

main().catch(console.error);
