workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    nusaai:
        inputs:
            - location: ./nusantara_openapi_v5.json
        registry:
            location: registry.speakeasyapi.dev/nusa-ai/sdk/nusaai
targets:
    my-target:
        target: typescript
        source: nusaai
