workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  nusaai:
    inputs:
      - location: registry.speakeasyapi.dev/nusa-ai/sdk/nusaai:1.0.0
targets:
  my-target:
    target: typescript
    source: nusaai
