/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Text atau array text untuk diembedding
 */
export type EmbeddingsRequestInput = string | Array<string>;

/**
 * Format encoding output
 */
export const EncodingFormat = {
  Float: "float",
  Base64: "base64",
} as const;
/**
 * Format encoding output
 */
export type EncodingFormat = ClosedEnum<typeof EncodingFormat>;

/**
 * Request untuk embeddings.
 */
export type EmbeddingsRequest = {
  /**
   * Nama model embeddings
   */
  model?: string | undefined;
  /**
   * Text atau array text untuk diembedding
   */
  input: string | Array<string>;
  /**
   * Format encoding output
   */
  encodingFormat?: EncodingFormat | undefined;
};

/** @internal */
export const EmbeddingsRequestInput$inboundSchema: z.ZodType<
  EmbeddingsRequestInput,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.string())]);

/** @internal */
export type EmbeddingsRequestInput$Outbound = string | Array<string>;

/** @internal */
export const EmbeddingsRequestInput$outboundSchema: z.ZodType<
  EmbeddingsRequestInput$Outbound,
  z.ZodTypeDef,
  EmbeddingsRequestInput
> = z.union([z.string(), z.array(z.string())]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EmbeddingsRequestInput$ {
  /** @deprecated use `EmbeddingsRequestInput$inboundSchema` instead. */
  export const inboundSchema = EmbeddingsRequestInput$inboundSchema;
  /** @deprecated use `EmbeddingsRequestInput$outboundSchema` instead. */
  export const outboundSchema = EmbeddingsRequestInput$outboundSchema;
  /** @deprecated use `EmbeddingsRequestInput$Outbound` instead. */
  export type Outbound = EmbeddingsRequestInput$Outbound;
}

export function embeddingsRequestInputToJSON(
  embeddingsRequestInput: EmbeddingsRequestInput,
): string {
  return JSON.stringify(
    EmbeddingsRequestInput$outboundSchema.parse(embeddingsRequestInput),
  );
}

export function embeddingsRequestInputFromJSON(
  jsonString: string,
): SafeParseResult<EmbeddingsRequestInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmbeddingsRequestInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmbeddingsRequestInput' from JSON`,
  );
}

/** @internal */
export const EncodingFormat$inboundSchema: z.ZodNativeEnum<
  typeof EncodingFormat
> = z.nativeEnum(EncodingFormat);

/** @internal */
export const EncodingFormat$outboundSchema: z.ZodNativeEnum<
  typeof EncodingFormat
> = EncodingFormat$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EncodingFormat$ {
  /** @deprecated use `EncodingFormat$inboundSchema` instead. */
  export const inboundSchema = EncodingFormat$inboundSchema;
  /** @deprecated use `EncodingFormat$outboundSchema` instead. */
  export const outboundSchema = EncodingFormat$outboundSchema;
}

/** @internal */
export const EmbeddingsRequest$inboundSchema: z.ZodType<
  EmbeddingsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  model: z.string().optional(),
  input: z.union([z.string(), z.array(z.string())]),
  encoding_format: EncodingFormat$inboundSchema.default("float"),
}).transform((v) => {
  return remap$(v, {
    "encoding_format": "encodingFormat",
  });
});

/** @internal */
export type EmbeddingsRequest$Outbound = {
  model?: string | undefined;
  input: string | Array<string>;
  encoding_format: string;
};

/** @internal */
export const EmbeddingsRequest$outboundSchema: z.ZodType<
  EmbeddingsRequest$Outbound,
  z.ZodTypeDef,
  EmbeddingsRequest
> = z.object({
  model: z.string().optional(),
  input: z.union([z.string(), z.array(z.string())]),
  encodingFormat: EncodingFormat$outboundSchema.default("float"),
}).transform((v) => {
  return remap$(v, {
    encodingFormat: "encoding_format",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EmbeddingsRequest$ {
  /** @deprecated use `EmbeddingsRequest$inboundSchema` instead. */
  export const inboundSchema = EmbeddingsRequest$inboundSchema;
  /** @deprecated use `EmbeddingsRequest$outboundSchema` instead. */
  export const outboundSchema = EmbeddingsRequest$outboundSchema;
  /** @deprecated use `EmbeddingsRequest$Outbound` instead. */
  export type Outbound = EmbeddingsRequest$Outbound;
}

export function embeddingsRequestToJSON(
  embeddingsRequest: EmbeddingsRequest,
): string {
  return JSON.stringify(
    EmbeddingsRequest$outboundSchema.parse(embeddingsRequest),
  );
}

export function embeddingsRequestFromJSON(
  jsonString: string,
): SafeParseResult<EmbeddingsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmbeddingsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmbeddingsRequest' from JSON`,
  );
}
