/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ServerErrorError = {
  message: string;
  type: string;
  code: string;
};

/** @internal */
export const ServerErrorError$inboundSchema: z.ZodType<
  ServerErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  type: z.string(),
  code: z.string(),
});

/** @internal */
export type ServerErrorError$Outbound = {
  message: string;
  type: string;
  code: string;
};

/** @internal */
export const ServerErrorError$outboundSchema: z.ZodType<
  ServerErrorError$Outbound,
  z.ZodTypeDef,
  ServerErrorError
> = z.object({
  message: z.string(),
  type: z.string(),
  code: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ServerErrorError$ {
  /** @deprecated use `ServerErrorError$inboundSchema` instead. */
  export const inboundSchema = ServerErrorError$inboundSchema;
  /** @deprecated use `ServerErrorError$outboundSchema` instead. */
  export const outboundSchema = ServerErrorError$outboundSchema;
  /** @deprecated use `ServerErrorError$Outbound` instead. */
  export type Outbound = ServerErrorError$Outbound;
}

export function serverErrorErrorToJSON(
  serverErrorError: ServerErrorError,
): string {
  return JSON.stringify(
    ServerErrorError$outboundSchema.parse(serverErrorError),
  );
}

export function serverErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<ServerErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerErrorError' from JSON`,
  );
}
