/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Metadata,
  Metadata$inboundSchema,
  Metadata$Outbound,
  Metadata$outboundSchema,
} from "./metadata.js";
import {
  ModelInfo,
  ModelInfo$inboundSchema,
  ModelInfo$Outbound,
  ModelInfo$outboundSchema,
} from "./modelinfo.js";

export type ModelsResponse = {
  object?: string | undefined;
  data?: Array<ModelInfo> | undefined;
  /**
   * Metadata response dari NusantaraAI.
   */
  metadata?: Metadata | undefined;
};

/** @internal */
export const ModelsResponse$inboundSchema: z.ZodType<
  ModelsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.string().optional(),
  data: z.array(ModelInfo$inboundSchema).optional(),
  _metadata: Metadata$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "_metadata": "metadata",
  });
});

/** @internal */
export type ModelsResponse$Outbound = {
  object?: string | undefined;
  data?: Array<ModelInfo$Outbound> | undefined;
  _metadata?: Metadata$Outbound | undefined;
};

/** @internal */
export const ModelsResponse$outboundSchema: z.ZodType<
  ModelsResponse$Outbound,
  z.ZodTypeDef,
  ModelsResponse
> = z.object({
  object: z.string().optional(),
  data: z.array(ModelInfo$outboundSchema).optional(),
  metadata: Metadata$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    metadata: "_metadata",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelsResponse$ {
  /** @deprecated use `ModelsResponse$inboundSchema` instead. */
  export const inboundSchema = ModelsResponse$inboundSchema;
  /** @deprecated use `ModelsResponse$outboundSchema` instead. */
  export const outboundSchema = ModelsResponse$outboundSchema;
  /** @deprecated use `ModelsResponse$Outbound` instead. */
  export type Outbound = ModelsResponse$Outbound;
}

export function modelsResponseToJSON(modelsResponse: ModelsResponse): string {
  return JSON.stringify(ModelsResponse$outboundSchema.parse(modelsResponse));
}

export function modelsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModelsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsResponse' from JSON`,
  );
}
