/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Metadata,
  Metadata$inboundSchema,
  Metadata$Outbound,
  Metadata$outboundSchema,
} from "./metadata.js";
import {
  ModelInfo,
  ModelInfo$inboundSchema,
  ModelInfo$Outbound,
  ModelInfo$outboundSchema,
} from "./modelinfo.js";

export type ModelsListResponse = {
  object?: string | undefined;
  data?: Array<ModelInfo> | undefined;
  metadata?: Metadata | undefined;
};

/** @internal */
export const ModelsListResponse$inboundSchema: z.ZodType<
  ModelsListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.string().optional(),
  data: z.array(ModelInfo$inboundSchema).optional(),
  _metadata: Metadata$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "_metadata": "metadata",
  });
});

/** @internal */
export type ModelsListResponse$Outbound = {
  object?: string | undefined;
  data?: Array<ModelInfo$Outbound> | undefined;
  _metadata?: Metadata$Outbound | undefined;
};

/** @internal */
export const ModelsListResponse$outboundSchema: z.ZodType<
  ModelsListResponse$Outbound,
  z.ZodTypeDef,
  ModelsListResponse
> = z.object({
  object: z.string().optional(),
  data: z.array(ModelInfo$outboundSchema).optional(),
  metadata: Metadata$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    metadata: "_metadata",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelsListResponse$ {
  /** @deprecated use `ModelsListResponse$inboundSchema` instead. */
  export const inboundSchema = ModelsListResponse$inboundSchema;
  /** @deprecated use `ModelsListResponse$outboundSchema` instead. */
  export const outboundSchema = ModelsListResponse$outboundSchema;
  /** @deprecated use `ModelsListResponse$Outbound` instead. */
  export type Outbound = ModelsListResponse$Outbound;
}

export function modelsListResponseToJSON(
  modelsListResponse: ModelsListResponse,
): string {
  return JSON.stringify(
    ModelsListResponse$outboundSchema.parse(modelsListResponse),
  );
}

export function modelsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModelsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsListResponse' from JSON`,
  );
}
