/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ModerationResult = {
  /**
   * Apakah konten terflag
   */
  flagged?: boolean | undefined;
  /**
   * Kategori yang terflag
   */
  categories?: { [k: string]: boolean } | undefined;
  /**
   * Skor setiap kategori
   */
  categoryScores?: { [k: string]: number } | undefined;
};

/** @internal */
export const ModerationResult$inboundSchema: z.ZodType<
  ModerationResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  flagged: z.boolean().optional(),
  categories: z.record(z.boolean()).optional(),
  category_scores: z.record(z.number()).optional(),
}).transform((v) => {
  return remap$(v, {
    "category_scores": "categoryScores",
  });
});

/** @internal */
export type ModerationResult$Outbound = {
  flagged?: boolean | undefined;
  categories?: { [k: string]: boolean } | undefined;
  category_scores?: { [k: string]: number } | undefined;
};

/** @internal */
export const ModerationResult$outboundSchema: z.ZodType<
  ModerationResult$Outbound,
  z.ZodTypeDef,
  ModerationResult
> = z.object({
  flagged: z.boolean().optional(),
  categories: z.record(z.boolean()).optional(),
  categoryScores: z.record(z.number()).optional(),
}).transform((v) => {
  return remap$(v, {
    categoryScores: "category_scores",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModerationResult$ {
  /** @deprecated use `ModerationResult$inboundSchema` instead. */
  export const inboundSchema = ModerationResult$inboundSchema;
  /** @deprecated use `ModerationResult$outboundSchema` instead. */
  export const outboundSchema = ModerationResult$outboundSchema;
  /** @deprecated use `ModerationResult$Outbound` instead. */
  export type Outbound = ModerationResult$Outbound;
}

export function moderationResultToJSON(
  moderationResult: ModerationResult,
): string {
  return JSON.stringify(
    ModerationResult$outboundSchema.parse(moderationResult),
  );
}

export function moderationResultFromJSON(
  jsonString: string,
): SafeParseResult<ModerationResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModerationResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModerationResult' from JSON`,
  );
}
