/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Role = {
  System: "system",
  User: "user",
  Assistant: "assistant",
  Tool: "tool",
} as const;
export type Role = ClosedEnum<typeof Role>;

export type TextMessage = {
  role: Role;
  content: string;
  name?: string | undefined;
  toolCallId?: string | undefined;
};

/** @internal */
export const Role$inboundSchema: z.ZodNativeEnum<typeof Role> = z.nativeEnum(
  Role,
);

/** @internal */
export const Role$outboundSchema: z.ZodNativeEnum<typeof Role> =
  Role$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Role$ {
  /** @deprecated use `Role$inboundSchema` instead. */
  export const inboundSchema = Role$inboundSchema;
  /** @deprecated use `Role$outboundSchema` instead. */
  export const outboundSchema = Role$outboundSchema;
}

/** @internal */
export const TextMessage$inboundSchema: z.ZodType<
  TextMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  role: Role$inboundSchema,
  content: z.string(),
  name: z.string().optional(),
  tool_call_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "tool_call_id": "toolCallId",
  });
});

/** @internal */
export type TextMessage$Outbound = {
  role: string;
  content: string;
  name?: string | undefined;
  tool_call_id?: string | undefined;
};

/** @internal */
export const TextMessage$outboundSchema: z.ZodType<
  TextMessage$Outbound,
  z.ZodTypeDef,
  TextMessage
> = z.object({
  role: Role$outboundSchema,
  content: z.string(),
  name: z.string().optional(),
  toolCallId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    toolCallId: "tool_call_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TextMessage$ {
  /** @deprecated use `TextMessage$inboundSchema` instead. */
  export const inboundSchema = TextMessage$inboundSchema;
  /** @deprecated use `TextMessage$outboundSchema` instead. */
  export const outboundSchema = TextMessage$outboundSchema;
  /** @deprecated use `TextMessage$Outbound` instead. */
  export type Outbound = TextMessage$Outbound;
}

export function textMessageToJSON(textMessage: TextMessage): string {
  return JSON.stringify(TextMessage$outboundSchema.parse(textMessage));
}

export function textMessageFromJSON(
  jsonString: string,
): SafeParseResult<TextMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextMessage' from JSON`,
  );
}
