/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UsageInfo = {
  used?: number | undefined;
  limit?: number | undefined;
  remaining?: number | undefined;
  resetAt?: Date | undefined;
};

/** @internal */
export const UsageInfo$inboundSchema: z.ZodType<
  UsageInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  used: z.number().int().optional(),
  limit: z.number().int().optional(),
  remaining: z.number().int().optional(),
  reset_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "reset_at": "resetAt",
  });
});

/** @internal */
export type UsageInfo$Outbound = {
  used?: number | undefined;
  limit?: number | undefined;
  remaining?: number | undefined;
  reset_at?: string | undefined;
};

/** @internal */
export const UsageInfo$outboundSchema: z.ZodType<
  UsageInfo$Outbound,
  z.ZodTypeDef,
  UsageInfo
> = z.object({
  used: z.number().int().optional(),
  limit: z.number().int().optional(),
  remaining: z.number().int().optional(),
  resetAt: z.date().transform(v => v.toISOString()).optional(),
}).transform((v) => {
  return remap$(v, {
    resetAt: "reset_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UsageInfo$ {
  /** @deprecated use `UsageInfo$inboundSchema` instead. */
  export const inboundSchema = UsageInfo$inboundSchema;
  /** @deprecated use `UsageInfo$outboundSchema` instead. */
  export const outboundSchema = UsageInfo$outboundSchema;
  /** @deprecated use `UsageInfo$Outbound` instead. */
  export type Outbound = UsageInfo$Outbound;
}

export function usageInfoToJSON(usageInfo: UsageInfo): string {
  return JSON.stringify(UsageInfo$outboundSchema.parse(usageInfo));
}

export function usageInfoFromJSON(
  jsonString: string,
): SafeParseResult<UsageInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageInfo' from JSON`,
  );
}
