name: Release Doctor
on:
  pull_request:
    branches:
      - speakeasy-sdk-regen-1749741977
  workflow_dispatch:

jobs:
  release_doctor:
    name: release doctor
    runs-on: ubuntu-latest
    if: github.repository == 'ErRickow/nusaai' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || startsWith(github.head_ref, 'release-please') || github.head_ref == 'next')

    steps:
      - uses: actions/checkout@v4

      - name: Check release environment
        run: |
          bash ./bin/check-release-environment
        env:
          STAINLESS_API_KEY: ${{ secrets.STAINLESS_API_KEY }}
          PYPI_TOKEN: ${{ secrets.NEOSANTARA_PYPI_TOKEN || secrets.PYPI_TOKEN }}
